### ISSUE TITLE
Search fails

### ISSUE THREAD

**Issue by vyp** [adrianchifor/Swiftnotes#12] opened 2015-02-19 15:22 UTC
Tapping the search icon does not seem to have any effect, whereas in the previous version (3.0.2), it worked fine. Can you reproduce?

**Comment by adrianchifor** [comment] 2015-02-19 15:25
It works fine for me on Nexus 5 and Nexus 7. What device are you using and what Android version?

**Comment by vyp** [comment] 2015-02-19 15:32
Galaxy s4 stock android version 4.3. I'm going to make sure 100% that it used to work in 3.0.2 now.

**Comment by adrianchifor** [comment] 2015-02-19 15:42
Just tested on 4.3 and 4.2 simulators, everything works fine. Try reinstalling the app or maybe a reboot? Should fix it.

**Comment by vyp** [comment] 2015-02-19 15:44
Okay this is interesting. The version 4.0.2 *on f-droid*, search works: tapping the search icon expands it into a search field. But 4.0.2 from this repo (https://github.com/adrianchifor/Swiftnotes/blob/20f91f4904799d4e2c488e9f73eccbd5ee31cd49/Swiftnotes_v302.apk) doesn't work. As doesn't 4.0.3 from this repo, which is the one I opened the issue for. 4.0.3 from play store also doesn't work. Will try rebooting now.

**Comment by vyp** [comment] 2015-02-19 15:53
Hmm rebooting doesn't work. I guess this might be a permissions issue? The f-droid one has access to where ever the app wants to search, whereas the github/play store versions don't? I tried deleting the `Swiftnotes` folder but that didn't work either. Do you know any app settings may be saved on the system so that I can delete them and retry? Will be interesting to see if 4.0.3 from f-droid works.

Closing because you can't reproduce, and because you confirmed the f-droid version should be the same as your one, meaning the fault is most definitely on my side.

**Comment by mrfanatic** [comment] 2015-02-20 20:11
*Tapping the search icon does not seem to have any effect*
I have the same problem on the play store version 3.0.3.
Using stock Jellybean 4.2.2

**Comment by adrianchifor** [comment] 2015-02-20 21:16
I might know what the problem is. I'll give it a look over the weekend and see what I can do. Thanks!

**Comment by vyp** [comment] 2015-02-21 19:18
Well there you go, search works normally in version 3.0.3 from f-droid. That pretty much confirms the issue is something to do with permissions/cache or similar? (at least my issue that is)

Also, I didn't say this before but after uninstalling 3.0.2 from f-droid and then reinstalling that later (version 3.0.2 still), f-droid didn't download the app from its repositories again, and just skipped straight to the "would you like to install screen", meaning it definitely stored it somewhere (at least temporarily), which might be causing the issue? It doesn't look like there's any setting to "purge" everything when uninstalling (from f-droid).

Anyhow, that's probably out of scope for you and a problem with f-droid instead, so feel free to close this if you want. But because I still want to use your apk's instead, if I find a solution for it, I'll post here again, for completions sake.

**Comment by adrianchifor** [comment] 2015-02-21 21:08
Thanks for letting me know. Again, I have no control over the f-droid repo and I do not recommend it because APKs are not verified for signatures/malware. I have looked over the implementation for search and I couldn't find anything bad with it. I even did proper unit testing and device full feature testing on 4.2, 4.3, 4.4 and lollipop on both phones and tables. Everything worked fine.

**Comment by vyp** [comment] 2015-02-22 10:55
No worries. Again, I would close this ticket but you reopened it (for @mrfanatic), so I'll leave it at that.

Also, this isn't about the issue at hand, but still related I think. While trying to search for solutions and figure out how f-droid works, I came across https://f-droid.org/wiki/page/FAQ_-_App_Developers#What_about_signing.3F and https://f-droid.org/wiki/page/FAQ_-_App_Developers#Can_APKs_signed_by_my_key_be_included.3F. Now as I said before, I don't know anything about developing/maintaining android apps, but that seems to suggest that f-droid actually builds all their apps from source (and signs them) themselves, and they don't allow apks not built by them on their official main repo.

I went ahead to look at their 'metadata' for your app (which they apparently use for their automated builds): https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/com.moonpi.swiftnotes.txt. Those commit hashes that you see refer to this github repo's commits. Now obviously, and especially because I don't know anything, this might all be able to be bypassed somehow, or maybe they might be lying (unlikely of course), but it doesn't seem as easy to be malicious with the f-droid version as I first thought.

Now that didn't solve the issue obviously, but felt like I should still share that though.

**Comment by adrianchifor** [comment] 2015-03-30 19:17
Found the bug that caused this problem: I was using simple MenuItem from AppCompat instead of MenuItemCompat from v4 support for the SearchView widget. Will close it for now. If anything else comes up, let me know. Thanks again for your help!

**Comment by vyp** [comment] 2015-03-31 08:44
Cool. But I tried your apk (the one uploaded in this repository, v311) and still had the same problem with regards to search. However, as I said before, I still think this is something wrong on my side rather than yours, so this issue should stay closed (at least for me, since I created it). I'm simply using the f-droid version now, since I never could find out what's wrong on my side, or how to fix it.

**Comment by adrianchifor** [comment] 2015-03-31 10:52
Oh...my...god. I just realised what the problem was. The ProGuard was obfuscating the support libraries in the release version and the SearchView was not getting properly initialised. Will push the new update now and should be available on the PlayStore very soon. The new APK will be on GitHub in a few minutes.

**Comment by adrianchifor** [comment] 2015-03-31 11:03
@vyp Let me know how it works now. You can get the APK here https://github.com/adrianchifor/Swiftnotes/raw/master/Swiftnotes_v312.apk. Thanks!

**Comment by mrfanatic** [comment] 2015-03-31 11:13
Yeah, search works now ( https://github.com/adrianchifor/Swiftnotes/raw/master/Swiftnotes_v312.apk ) :+1:

**Comment by adrianchifor** [comment] 2015-03-31 11:15
@mrfanatic Awesome!

**Closed by adrianchifor** 2015-03-31 11:15 UTC

**Comment by vyp** [comment] 2015-03-31 11:22
@adrianchifor Ah well turns out it was a bug! Works perfectly now, awesome! :D
